Instance discovery with etcd
INAETICS/Drones-Simulator pull request #53
Opened 2017-05-17 10:06 UTC by jjkester

2017-05-17 11:01 UTC, ghost requested changes

2017-05-17 11:01 UTC, Fathardie commented on implementation/discovery/etcd/src/main/java/org/inaetics/dronessimulator/discovery/etcd/EtcdConfigDiscoverer.java
> +        String name = pathSegments[2];
Idee om eerst pathSegments.length te checken en als deze !=3 een exceptie te gooien? (Of i.i.g. te loggen?)

2017-05-17 12:37 UTC, jjkester commented on implementation/discovery/etcd/src/main/java/org/inaetics/dronessimulator/discovery/etcd/EtcdConfigDiscoverer.java
> +        String name = pathSegments[2];
Loggen is een goed idee (want probably verkeerde configuratie). In principe zorgt de methode ervoor dat hij atlijd 3 lang is, maar een check maakt het zeker robuuster.

2017-05-19 07:56 UTC, ghost approved these changes

2017-05-19 08:00 UTC, merged