Visualisation zooming panning
INAETICS/Drones-Simulator pull request #58
Opened 2017-05-22 15:12 UTC by Langstra

This adds explosions when drones are killed.
Zooming and panning is supported.
Drones scale based on their height. Higher drones appear larger, lower drones appear smaller.

2017-05-22 15:29 UTC, jjkester requested changes
In general some more documentation might be nice

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/BaseEntity.java
> + * Created by langstra on 22-5-17.
Better to remove or change this.

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/BaseEntity.java
> +    int width;
No visibility settings here - intentional (package-private) or forgotten?

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/Bullet.java
> + * Created by langstra on 22-5-17.
Please remove or change this to something useful

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/Game.java
> +//                    System.out.println("Average: " + durationAverageMs);
Either log it as debug or remove these lines altogether.

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/controls/SceneGestures.java
> +
Unnecessary whitespace

2017-05-22 15:29 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/controls/SceneGestures.java
> +
Here, and in lines above, unnecessary whitespace

2017-05-23 13:50 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/SpriteAnimation.java
> + * Creates an animation based on a sprite
"Creates" is not suitable in this context (class).

2017-05-23 13:50 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/Settings.java
>  public class Settings {
(Did not see last time) Maybe change this to VisualisationSettings?

2017-05-23 13:50 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/BaseEntity.java
>  public abstract class BaseEntity {
Would be nice to have this class documented as well.

2017-05-23 14:52 UTC, Langstra commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/SpriteAnimation.java
> + * Creates an animation based on a sprite
The constructor describes this also, I think I leave it out.

2017-05-23 14:53 UTC, Langstra commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/Settings.java
>  public class Settings {
It is already in the visualisation package, shouldn't that be enough? If it is a convention, then sure, it can be refactored.

2017-05-23 14:55 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/SpriteAnimation.java
> + * Creates an animation based on a sprite
A more appropriate description would be to say "Represents an animation..."

2017-05-23 14:56 UTC, jjkester commented on implementation/visualisation/src/main/java/org/inaetics/dronessimulator/visualisation/Settings.java
>  public class Settings {
I am not in favor of too long and descriptive class names, but I think that in this case Settings is not descriptive enough (settings for what)? It is kind of fine but I like a bit more description a bit better.

2017-05-24 09:01 UTC, jjkester approved these changes

2017-05-26 10:52 UTC, merged